name: "Run Script Every 7 Days"

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日的 0:00 AM 运行
  workflow_dispatch:

jobs:
  update-rule-set:
    name: "Update sing-box rule-set"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup sing-box"
        env:
          SING_BOX_DEB_URL: "https://github.com/SagerNet/sing-box/releases/download/v1.9.4/sing-box_1.9.4_linux_amd64.deb"
        run: |
            set -Eeuo pipefail
            wget -O sing-box.deb $SING_BOX_DEB_URL
            sudo dpkg -i sing-box.deb
      - name: "Setup python venv"
        run: |
            set -Eeuo pipefail
            python3 -m venv venv
            source venv/bin/activate
            pip3 install requests
      - name: "Update rule-set"
        run: |
            set -Eeuo pipefail
            source venv/bin/activate
            python3 do.py
      - name: "Commit and push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            set -Eeuo pipefail
            cd main
            git init
            git config --local user.name "github-actions[bot]"
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit --allow-empty-message --no-edit
            git branch -M main
            git remote add origin https://github-action:$GITHUB_TOKEN@github.com/HiRules/sing-box-blacklist.git
            git push -u origin main --force
