name: "test"

on:
  workflow_dispatch:

jobs:
  update-rule-set:
    name: "test"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Setup python venv"
        run: |
            set -Eeuo pipefail
            python3 -m venv venv
            source venv/bin/activate
            
      - name: "Update test"
        run: |
            set -Eeuo pipefail
            source venv/bin/activate
            python3 test.py
      - name: "Commit and push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
